version: '3.9'

services:
  ml-service:
    build: ./backend/ml-service
    volumes:
      - ./model-ml/no_show_model.pkl:/app/model/no_show_model.pkl:ro
    ports:
      - "8005:8000"

  booking-service-java:
    build: ./app-java/booking-service
    environment:
      ML_BASE_URL: http://ml-service:8000
    depends_on:
      - ml-service
    ports:
      - "8083:8083"